CREATE TABLE IF NOT EXISTS `TRANSAN_TRANSFER_AUDITS` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `transan_id` INT(11) NOT NULL,
    `accion` VARCHAR(32) NOT NULL,
    `fecha_evento` DATETIME NOT NULL,
    `usuario_id` INT(11) NULL,
    `usuario_nombre` VARCHAR(200) NULL,
    `usuario_rol` VARCHAR(60) NULL,
    `vendedor_id` INT(11) NULL,
    `comprador_id` INT(11) NULL,
    `plantel_origen_id` INT(11) NULL,
    `plantel_destino_id` INT(11) NULL,
    `vendedor_codigo` VARCHAR(20) NULL,
    `comprador_codigo` VARCHAR(20) NULL,
    `plantel_origen` VARCHAR(20) NULL,
    `plantel_destino` VARCHAR(20) NULL,
    `plantel_origen_codigo` VARCHAR(20) NULL,
    `plantel_origen_anioex` VARCHAR(4) NULL,
    `plantel_destino_codigo` VARCHAR(20) NULL,
    `plantel_destino_anioex` VARCHAR(4) NULL,
    `bucket_campo` VARCHAR(20) NULL,
    `bucket_etiqueta` VARCHAR(120) NULL,
    `tiphac` VARCHAR(10) NULL,
    `hemsta` VARCHAR(10) NULL,
    `tipohem` VARCHAR(10) NULL,
    `cant_hem` INT(11) NULL,
    `cant_mach` INT(11) NULL,
    `cant_chem` INT(11) NULL,
    `cant_cmach` INT(11) NULL,
    `origen_antes` DOUBLE NULL,
    `origen_despues` DOUBLE NULL,
    `destino_antes` DOUBLE NULL,
    `destino_despues` DOUBLE NULL,
    `mail_vendedor` VARCHAR(255) NULL,
    `mail_comprador` VARCHAR(255) NULL,
    `mail_estado` VARCHAR(40) NULL,
    `mail_error` LONGTEXT NULL,
    `detalle` LONGTEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_transan_transfer_audits_transan_id` (`transan_id`),
    KEY `idx_transan_transfer_audits_fecha_evento` (`fecha_evento`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
